### ISSUE TITLE
Error in x[i, ] : subscript out of bounds

### ISSUE THREAD

**Issue by kaikrautter** [taktsun/dissimilarity-for-ESM-data#1]
Hi! Great package and paper. I'm reaching out because I'm getting an error message when I run your sample code for the Blanke et  al. 2020 paper (and also when I'm adapting it to my own dataset): 

`Error in x[i, ] : subscript out of bounds`

Do you have an idea why this could be?

Thanks!

**Comment by taktsun** [comment]
Hi! Sorry for the late reply but this issue has been fixed in the 20240123 version of the script. The previous version hardcoded the pid at some point as ppnr.
